codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true

ignore:
  - "**/__tests__/**"        # Exclude all test files
  - "**/*.test.{js,jsx,ts,tsx}"  # Exclude test files
  - "**/node_modules/**"     # Exclude node_modules
  - "build/**"               # Exclude build output
  - "dist/**"                # Exclude distribution files
  - "coverage/**"            # Exclude coverage reports
  - "src/serviceWorker.ts"   # Exclude service worker
  - "src/reportWebVitals.ts" # Exclude web vitals reporting
  - "src/setupTests.ts"      # Exclude test setup
  - "**/*.stories.{js,jsx,ts,tsx}" # Exclude storybook files
  - "src/mocks/**"           # Exclude mock files
  - "public/**"              # Exclude public assets
  - "**/*.d.ts"              # Exclude declaration files
  - "src/index.tsx"          # Main entry point (often just bootstraps the app)
  - "src/environments/firebase-config.ts" # Firebase configuration
  - "src/service-worker.ts"  # Service worker implementation
  - "src/serviceWorkerRegistration.ts"  # Service worker registration
  - "src/setup.js"           # Setup file
  - "src/utils/firebase.mocks.ts"
  - "src/utils/debugFCM.ts"